const activities = [
    {
        id: 'activity1',
        name: '5GX Reverse Bungy',
        location: 'Denpasar, Bali',
        guestsAllowed: 4,
        dateAvailable: '2024-12-15',
        price: '700.000',
        priceForFilter: 700000,
        image: 'images/5gx.png',
        image2: 'images/5gx-2.jpg',
        image3: 'images/5gx-3.jpg',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3943.7228560403705!2d115.17190207382235!3d-8.717845788878803!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd246c6c2b664e3%3A0x87bf7e718fc653ec!2s5GX%20Bali!5e0!3m2!1sen!2sid!4v1732770284848!5m2!1sen!2sid',
        rating: '4.9 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'air',
        openHours: '8 am - 5 pm',
        description: "5GX Bali Reverse Bungy is a slingshot ride offering an adrenaline-inducing experience in Bali. The capsule is catapulted 50 metres into the air at mind-boggling speed around 200 km/h.",
        details: {
            highlights: [
                "Each ride can accommodate 3 people at a time, with each being strapped into the capsule while on the ground.",
                "There’s a camera directly in front of the seats that takes your photo during the ride – you can purchase it as a memento of your experience.",
            ],
            packages: [
                { title: "5GX Ride for 2", price: 700000, location: 'Denpasar, Bali', person: 2, image: 'images/5gx.png'},
                { title: "5GX Ride for 3", price: 1200000, location: 'Denpasar, Bali', person: 3, image: 'images/5gx.png'},
            ],
            activityInfo: [
                { title: "Full Description", description: "5GX Reverse Bungy is a slingshot ride offering an adrenaline-inducing experience in Bali. Each ride can accommodate 3 people at a time, with each being strapped into the capsule while on the ground. At the press of a button, the capsule is catapulted 50 metres into the air at a mind-boggling speed around 200 km/h." },
                { title: "Includes", description: "1x ride to 5GX Bali for 2 person, duration: approximately 3-5 minutes." },
                { title: "Not suitable for", description: [
                    "Age over 60",
                    "Age below 10",
                    "Pregnant woman",
                    "People with a history of heart disease and high blood pressure",
                ] },
                { title: "Note", description: [
                    "There’s a camera directly in front of the seats that takes your photo during the ride - you can purchase a print as a memento of your experience.",
                    "Avoid wearing accessories and sandals",
                    "Wait at least two hours after eating",
                ] },
            ],
            risks: [
                "This activity doesn't have insurance and you are required to sign the agreement before riding reverse bungy at 5GX Bali.",
                "Minor injuries like scratches on the neck because of the seatbelt, etc.",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "How high is the 5GX?", answer: "The 5GX is 35 meters high." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "How fast is the 5GX?", answer: "The 5GX goes as fast as 200km/h." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "Is it safe? What is the safety procedure?", answer: "The team of 5GX Bali Reverse Bungy really makes sure of the safety of the passengers. You will be secured well into your seats using an airplane safety lap belt, and the staff will triple-check the belt." },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "When is the best time to try the 5GX Reverse Bungy?", answer: "It is recommended to try Bali's 5GX Reverse Bungy ride in the afternoon, as you can see the sunset when the ride flies up to 50 meters. If you try the ride at night, then you will be able to see the lights all around Jalan Legian Kuta." },
            ],
            hotelsNearby: [
                "HARPER Kuta Bali",
                "The Niche Bali",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Courage",
            ],
        },
    },
    {
        id: 'activity2',
        name: 'Fun Jet Ski and Water Sport',
        location: 'Tanjung Benoa, Bali',
        guestsAllowed: 2,
        dateAvailable: '2024-12-10',
        price: '600.000',
        priceForFilter: 600000,
        image: 'images/jetski.png',
        image2: 'images/jetSki2.jpg',
        image3: 'images/jetski3.jpg',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3943.3136498825615!2d115.21929997382303!3d-8.756531189391708!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd24323ab636f7f%3A0x94187d63779e7332!2sJetski%20Touring%20Fun%20Day%20Nusa%20Dua!5e0!3m2!1sen!2sid!4v1732770325492!5m2!1sen!2sid',
        rating: '4.7 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'water',
        openHours: '8 am - 5 pm',
        description: "Enjoy the thrill on surfing at the ocean at high speed.",
        details: {
            highlights: [
                "Each ride can accomodate 2 people at a time.",
            ],
            packages: [
                { title: "Jet ski Ride for 2", price: 700000, location: 'Tanjung Benoa, Bali', person: 2, image: 'images/jetski.png' },
                { title: "Jet ski Ride for 3", price: 1200000, location: 'Tanjung Benoa, Bali', person: 3, image: 'images/jetski.png' },
            ],
            activityInfo: [
                { title: "Full Description", description: "full desc about fun jet ski and water sports" },
                { title: "Includes", description: "includes about fun jet ski and water sports" },
                { title: "Not suitable for", description: [
                    "Age over 60",
                    "Age below 10",
                    "Pregnant woman",
                    "People with a history of heart disease and high blood pressure",
                ] },
                { title: "Note", description: [
                    "Avoid wearing accessories and sandals",
                    "Wait at least two hours after eating",
                ] },
            ],
            risks: [
                "This activity doesn't have insurance and you are required to sign the agreement before riding Fun jet ski and water sports.",
                "Minor injuries like scratches on the neck because of the seatbelt, etc.",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "How fast is the jet ski?", answer: "The jet ski goes as fast as 100km/h." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "Is it safe? What is the safety procedure?", answer: "The team of Fun Jet Ski and Water Sports really makes sure of the safety of the passengers." },
            ],
            hotelsNearby: [
                "The Laguna",
                "Suites & Villas at Sofitel Bali Nusa Dua",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Spare clothes",
                "Sunblock",
            ],
        },
    },
    {
        id: 'activity3',
        name: 'Fly Board Experience',
        location: 'Denpasar, Bali',
        guestsAllowed: 1,
        dateAvailable: '2024-12-20',
        price: '1.200.000',
        priceForFilter: 1200000,
        image: 'images/flyboard1.png',
        image2: 'images/flyboard2.jpeg',
        image3: 'images/flyboard3.jpeg',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3942.8958808178963!2d115.23378709999999!3d-8.795851949999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd243213c2ea8df%3A0xfe9b8fbae7a12e8f!2sNusa%20Dua%20Beach!5e0!3m2!1sen!2sid!4v1732770008049!5m2!1sen!2sid',
        rating: '4.5 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'water',
        openHours: '8 am - 4 pm',
        description: "Embark on an extraordinary adventure at Nusa Dua Beach with our Fly Board Water Sport Experience. Imagine soaring above the crystalline waters, propelled by cutting-edge fly board technology. Whether you're a first-timer or an experienced thrill-seeker, our expert instructors ensure a safe and exhilarating experience. With state-of-the-art equipment and the stunning backdrop of Bali's coastline, this activity promises an adrenaline-pumping adventure and unforgettable memories.",
        details: {
            highlights: [
                "Gravity-Defying Thrills: Experience the unparalleled excitement of fly boarding",
                "Cutting-Edge Technology: Immerse yourself in the future of water sports",
                "Expert Guidance: Our skilled instructors cater to all skill levels",
            ],
            packages: [
                { title: "One person", price: 550000, location: 'Denpasar, Bali', person: 1, image: 'images/flyboard1.png' },
                { title: "One person (with pickup and dropoff)", price: 950000, location: 'Denpasar, Bali', person: 1, image: 'images/flyboard1.png' },
                { title: "Plan Together (10 person)", price: 5000000, location: 'Denpasar, Bali', person: 10, image: 'images/flyboard1.png' },  
            ],
            activityInfo: [
                { title: "Full Description", description: "Embark on an extraordinary adventure at Nusa Dua Beach with our Fly Board Water Sport Experience. Imagine soaring above the crystalline waters, propelled by cutting-edge fly board technology. Whether you're a first-timer or an experienced thrill-seeker, our expert instructors ensure a safe and exhilarating experience. With state-of-the-art equipment and the stunning backdrop of Bali's coastline, this activity promises an adrenaline-pumping adventure and unforgettable memories." },
                { title: "Includes", description: "Activities equipment, locker, shower, towel, changing room, insurance" },
                { title: "Not suitable for", description: [
                    "Children under 10 years",
                    "People over 65 years",
                ] },
                { title: "Note", description: [
                    "After you arrive please go inside and find person named Mrs. Silvi",
                ] },
            ],
            risks: [
                "Risk of injury due to falls or collisions",
                "Risk of drowning in case of equipment malfunction",
                "Potential damage to equipment or property",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "Will I be able to set this up or is it too complex and requires specialized tools?", answer: "Fortunately, all flyboarding systems are very straightforward to set up. With basic tools (socket and allen wrench set), you can remove the stock steering system from the PWC to install the flyboarding adapter (this typically takes 30 minutes to 1 hour). From there, it’s a simple two-minute process to hook up the u-pipe and hose to get flying." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "Is flyboarding safe?", answer: "Flyboarding is actually much safer than many other activities on the water, such as jet skiing and wakeboarding." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "Will I actually be able to do this or is it just for extreme athletes?", answer: "Many people assume it’s just for “extreme athletes” or people with great balance, but the majority of first-time pilots are airborne within their first five minutes and many people are diving, spinning and flipping by the end of their first flights." },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "Will my whole family be able to fly and have fun?", answer: "Most first-time pilots are airborne within their first five minutes, so it’s easy to learn, and despite what many people think, it doesn’t require tremendous amounts of balance." },
            ],
            hotelsNearby: [
                "The Laguna",
                "Suites & Villas at Sofitel Bali Nusa Dua",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Spare clothes",
                "Sunblock",
            ],
        },
    },
    {
        id: 'activity4',
        name: 'ATV Quad Bike Adventure',
        location: 'Ubud, Bali',
        guestsAllowed: 10,
        dateAvailable: '2024-12-20',
        price: '460.000',
        priceForFilter: 460000,
        image: 'images/atvride.png',
        image2: 'images/atv quad bike 1.jpeg',
        image3: 'images/atv quad bike2.jpeg',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3945.3237616254964!2d115.2538828!3d-8.5648341!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd23d472991fdd9%3A0x18e0c06af55de64c!2sATV%20Ubud%20Bali!5e0!3m2!1sen!2sid!4v1732770191712!5m2!1sen!2sid',
        rating: '4.5 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'land',
        openHours: '8 am - 5 pm',
        description: "Explore this tropical paradise as you discover its varied landscapes, lush rice paddies, overgrown jungles and rushing rivers on by the ATV Quad bike adventure.",
        details: {
            highlights: [
                "Explore the natural landscape dotted with rice fields, jungles, rivers, and local villages",
                "Be guided through the track by an experienced and professional guide",
                "Challenge yourself by traversing slopes, steep inclines, and bumpy terrain",
            ],
            packages: [
                { title: "Single ATV Ride", price: 460000, location: 'Ubud, Bali', person: 1, image: 'images/atvride.png' },
                { title: "Tandem ATV Ride", price: 690000, location: 'Ubud, Bali', person: 1, image: 'images/atvride.png' },
                { title: "Plan Together (10 person)", price: 4000000, location: 'Ubud, Bali', person: 10, image: 'images/atvride.png' },
            ],
            activityInfo: [
                { title: "Full Description", description: "Explore this tropical paradise as you discover its varied landscapes, lush rice paddies, overgrown jungles and rushing rivers on by the ATV Quad bike adventure. \nChoose to either ride in tandem with a companion or drive your own buggy each - either way, you’ll be treated to a spectacular sight of Bali’s natural beauty as you drive through and around the extensive track." },
                { title: "Includes", description: "Helmet, boots, 250 cc ATV for 1.5 hour" },
                { title: "Not suitable for", description: [
                    "age below 10 and over 60",
                    "pregnant woman",
                    "people with history of heart disease and high blood pressure",
                ] },
                { title: "Note", description: [
                    "If you’re up for a bit more thrill, just let your guide know and he’ll take you to a more technical terrain where you can make your way up steep hills on full speed or slide down slopes as you please.",
                ] },
            ],
            risks: [
                "Insurance and safety equipment included",
                "Public health risks: orthopedic injuries",
                "Sunburns from outdoor tracks",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "How long is the duration of the trip?", answer: "1.5 hours." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "How fast is the ATV?", answer: "50-90 miles per hour " },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "Is it safe? What is the safety procedure?", answer: "There will be two guides that will follow you throughout the trip on the front and on the back of the line. And there will be staffs along the track." },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "When is the best time to try the ATV?", answer: "8 am until 5 pm" },
            ],
            hotelsNearby: [
                "Dewa Bali Apartment",
                "Semimpi Hotel Bali",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Spare clothes",
                "Sunblock",
            ],
        },
    },
    {
        id: 'activity5',
        name: 'Ubud ATV Extreme Trek',
        location: 'Ubud, Bali',
        guestsAllowed: 12,
        dateAvailable: '2024-12-20',
        price: '620.000',
        priceForFilter: 620000,
        image: 'images/atvExtremeTrek.jpeg',
        image2: 'images/atv extreme 2.jpeg',
        image3: 'images/atv extreme 3.jpeg',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3945.323043970011!2d115.2554256!3d-8.5649033!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd23d5440eb2e89%3A0x5c38df970a149312!2sATV%20Ubud%20Adventure!5e0!3m2!1sen!2sid!4v1732770380174!5m2!1sen!2sid',
        rating: '4.5 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'land',
        openHours: '8 am - 5 pm',
        description: "Pump up your adrenaline and explore the wild side of Bali and its rural areas with an ATV ride. The UBUD ATV Extreme Trek program invites you to traverse the Ubud forest on an ATV through more challenging and exhilarating trails. This trek is perfect for those seeking an ATV adventure in Ubud with more demanding routes and adrenaline-pumping thrills. The ATV trail passes through Ubud's tropical forests, bamboo groves, cliffs, rivers, banana plantations, rice fields, and villages.",
        details: {
            highlights: [
                "5 sessions available: 10 am, 11 am, 1 pm, 2 pm, and 3 pm",
                "Minimal booking: 2 persons",
                "Before we start, our guide will show you the tutorial on how to ride the ATV and keep you safe.",
            ],
            packages: [
                { title: "Single Ride", price: 620000, location: 'Ubud, Bali', person: 1, image: 'images/atvExtremeTrek.jpeg' },
                { title: "Tandem Ride", price: 1100000, location: 'Ubud, Bali', person: 1, image: 'images/atvExtremeTrek.jpeg' },
                { title: "Plan Together (12 persons)", price: 7000000, location: 'Ubud, Bali', person: 12, image: 'images/atvExtremeTrek.jpeg' },
            ],
            activityInfo: [
                { title: "Full Description", description: "Pump up your adrenaline and explore the wild side of Bali and its rural areas with an ATV ride. The UBUD ATV Extreme Trek program invites you to traverse the Ubud forest on an ATV through more challenging and exhilarating trails. This trek is perfect for those seeking an ATV adventure in Ubud with more demanding routes and adrenaline-pumping thrills. The ATV trail passes through Ubud's tropical forests, bamboo groves, cliffs, rivers, banana plantations, rice fields, and villages." },
                { title: "Includes", description: "Transport pickup & back hotel, ATV equipments, Guide, Shower, Lunch, Locker, Insurance " },
                { title: "Not suitable for", description: [
                    "age below 10 and over 60",
                    "pregnant woman",
                    "people with history of heart disease and high blood pressure",
                ] },
                { title: "Note", description: [
                    "A 3% bank fee will be added to all transactions made with credit cards.",
                ] },
            ],
            risks: [
                "Insurance and safety equipment included",
                "Public health risks: orthopedic injuries",
                "Sunburns from outdoor tracks",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "How long is the duration of the trip?", answer: "1.5 hours." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "How fast is the ATV?", answer: "50-90 miles per hour " },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "Is it safe? What is the safety procedure?", answer: "There will be two guides that will follow you throughout the trip on the front and on the back of the line. And there will be staffs along the track." },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "When is the best time to try the ATV?", answer: "8 am until 5 pm" },
            ],
            hotelsNearby: [
                "Sthala, a Tribute Portfolio Hotel",
                "The Westin",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Spare clothes",
                "Sunblock",
            ],
        },
    },
    {
        id: 'activity6',
        name: 'Rock Climbing Experience',
        location: 'Kuta, Bali',
        guestsAllowed: 2,
        dateAvailable: '2024-12-15',
        price: '1.100.000',
        priceForFilter: 1100000,
        image: 'images/rockclimbing.png',
        image2: 'images/Rock Climbing 2.png',
        image3: 'images/Rock Climbing 3.jpg',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3948.9385296739933!2d115.3797132738128!3d-8.208936882357763!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd1f12c1276d349%3A0x9860e3db91b74a4d!2sGREATROCK%20BALI%20ADVENTURE%20%3A%20Rock%20Climbing%20Excursion%20%7C%20Songan%20Crag!5e0!3m2!1sen!2sid!4v1732770495102!5m2!1sen!2sid',
        rating: '4.9 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'land',
        openHours: '11 am - 6 pm',
        description: "Feel the thrill of climbing cliffs in Bali while being guided by experienced guides and gain more new experiences in rock climbing. Diverse routes are available for different levels of rock climbers.",
        details: {
            highlights: [
                "Climb the cliffs of Bali for an adrenaline rush with stunning views",
                "Diverse routes are suitable for all levels in a dynamic climbing community",
                "An immersive experience, combining the thrill of climbing with the serenity of unexplored beauty",
            ],
            packages: [
                { title: "One Person", price: 1100000, location: 'Kuta, Bali', person: 1, image: 'images/rockclimbing.png' },
                { title: "One Person Plus Hot Spring Bath", price: 1300000, location: 'Kuta, Bali', person: 1, image: 'images/rockclimbing.png' },
                { title: "Two Persons", price: 2200000, location: 'Kuta, Bali', person: 2, image: 'images/rockclimbing.png' },
            ],
            activityInfo: [
                { title: "Full Description", description: "Feel the thrill of climbing cliffs in Bali while being guided by experienced guides and gain more new experiences in rock climbing. Diverse routes are available for different levels of rock climbers." },
                { title: "Includes", description: "Entry access to tourist attractions, Staff who master English, Staff who master Indonesian, Transportation to and from hotel, All Rock Climbing Equipment, Professional Guide" },
                { title: "Not suitable for", description: [
                    "Participants must be at least 17+ years of age to participate in this activity",
                    "Participants must be under 65 years of age to take part in this activity Intermediate level fitness is required to participate in this activity",
                    "Participants must weigh between 10 kg - 100 kg to be able to take part in this activity",
                ] },
                { title: "Note", description: [
                    "Although not required, you should purchase accident insurance and/or travel insurance to participate in this activity",
                ] },
            ],
            risks: [
                "Falling. It is not that risky, but still a fact to keep in mind",
                "Skin Abrasions & Injuries. Minor bumps and bruises on the skin are not that big a danger.",
                "Bumping into Other Climbers.",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "How long will the journey take from the pickup spot to the rock climbing spot?", answer: "1.5 hours." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "What if its raining when we are about to go to the hot springs?", answer: "Will proceed with caution." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "Is it safe? What is the safety procedure?", answer: "There will be two guides that will follow you throughout the trip on the front and on the back of the line. And there will be staffs along the track." },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "Are the gears provided safe?", answer: "Yes all of the gears have been triple checked." },
            ],
            hotelsNearby: [
                "Volcano Cabin Batur Red Partner",
                "Pinggan Luxury Camp",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Sunblock",
                "Spare Clothes",
            ],
        },
    },
    {
        id: 'activity7',
        name: 'Annual Bali Skydiving',
        location: 'Kuta, Bali',
        guestsAllowed: 12,
        dateAvailable: '2024-12-10',
        price: '20.000.000',
        priceForFilter: 20000000,
        image: 'images/skydiving.png',
        image2: 'images/skydiving2.jpeg',
        image3: 'images/skydiving3.jpeg',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3943.8844709308587!2d115.18191837382206!3d-8.702520088676227!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd2411a35d0c1dd%3A0xa3b601fb188b3093!2siFLY%20Bali!5e0!3m2!1sen!2sid!4v1732770559011!5m2!1sen!2sid',
        rating: '4.7 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'air',
        openHours: '11 am - 7 pm',
        description: "AMAZING Bali skydive, possible for just one week in the whole year in June only with special permissions from the Airforce & Government of Indonesia where you will get to jump out of a Long tail Hercules C-130 Giant military airplane that carries 90 jumpers inside it at once!",
        details: {
            highlights: [
                "Open To Everyone, No Prior Skydiving Experience Needed",
                "5 Nights / 6 Days Package",
                "Only possible in June 2024 for one week",
            ],
            packages: [
                { title: "One Person", price: 20000000, location: 'Kuta, Bali', person: 1, image: 'images/skydiving.png' },
                { title: "Two Person", price: 35000000, location: 'Kuta, Bali', person: 2, image: 'images/skydiving.png' },
                { title: "Plan Together (12 persons)", price: 220000000, location: 'Kuta, Bali', person: 12, image: 'images/skydiving.png' },
            ],
            activityInfo: [
                { title: "Full Description", description: "AMAZING Bali skydive, possible for just one week in the whole year in June only with special permissions from the Airforce & Government of Indonesia where you will get to jump out of a Long tail Hercules C-130 Giant military airplane that carries 90 jumpers inside it at once!" },
                { title: "Includes", description: "5 Nights/6 days accommodation in Bali, One Tandem Skydive from a GIANT military Hercules C-130 aircraft, Government and Military permits and permissions, Video, Airport Transfers" },
                { title: "Not suitable for", description: [
                    "age below 10 and over 60",
                    "pregnant woman",
                    "people with history of heart disease and high blood pressure",
                ] },
                { title: "Note", description: [
                    "No other dates or months are possible for this skydive since it is an annual skydiving event / trip we are organizing with special permits from the government of Indonesia, skydiving in Bali is not available in general or throughout the year.",
                ] },
            ],
            risks: [
                "parachute malfunctions",
                "medical concerns acting up during the jump",
                "mid-air collisions",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "What will I do there apart from this Skydive In Bali?", answer: "One one of the days you will get to do your epic Bali skydive and the other 3 days are for sightseeing and everything else" },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "What’s the weather like in Bali?", answer: "June is one of the best times of the year in Bali with beautiful and sunny summer weather." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "But I have never done skydiving before, can I come?", answer: "This annual Skydive Bali trip is open to beginners who can come do a “tandem skydive” tied up in a harness together with one of our many World Class Skydiving Instructors from around the globe that we will fly down to Bali/Indonesia for this event/trip." },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "Why does this trip seem expensive?", answer: "Prices of skydives around the world vary wildly and depend on logistics, permissions and various other factors listed below." },
            ],
            hotelsNearby: [
                "Already includes hotel",
            ],
            howToGetThere: [
                "Already include transfers",
            ],
            whatYouNeed: [
                "Courage",
            ],
        },
    },
    {
        id: 'activity8',
        name: 'Manta Bay Snoekeling',
        location: 'Nusa Lembongan, Bali',
        guestsAllowed: 10,
        dateAvailable: '2024-12-20',
        price: '393.750',
        priceForFilter: 393750,
        image: 'images/MantaBaySnorkeling.webp',
        image2: 'images/Manta Bay Snorkeling2.webp',
        image3: 'images/Manta Bay Snorkeling3.webp',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15777.096587177928!2d115.46293220000003!3d-8.665457099999994!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd26d5063824477%3A0xa0eec80d3e1b278d!2sLembongan%20Snorkeling%20Trips!5e0!3m2!1sen!2sid!4v1732770619076!5m2!1sen!2sid',
        rating: '4.5 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'water',
        openHours: '9 am - 11 am',
        description: "Start your adventure with a comfortable shuttle service to hotels in the area. Upon arrival at the pier, you will meet a guide who will provide safety guidance. Next, you will receive snorkeling equipment. Feel the excitement of swimming with various types of colorful tropical fish and beautiful coral reefs in the waters of Manta Bay, Crystal Bay and Toyapakeh Wall Penida. If you're lucky, you can also see a 5 meter wide stingray passing through the shallow sea!",
        details: {
            highlights: [
                "The waters around Nusa Penida and Nusa Lembongan offers you a snorkeling experience like no other.",
                "This area is home to coral reefs and various marine life such as turtles, seahorses, and much more!",
                "Don't forget to stop by Manta Bay in Nusa Lembongan, where stingrays swim beautifully.",
            ],
            packages: [
                { title: "One person Snorkeling Tour (start from Mangrove Beach Nusa Lembongan)", price: 393750, location: 'Nusa Lembongan, Bali', person: 1, image: 'images/MantaBaySnorkeling.webp' },
                { title: "One person Snorkeling & Island Tour (start from Sanur Harbour)", price: 731250, location: 'Nusa Lembongan, Bali', person: 1, image: 'images/MantaBaySnorkeling.webp' },
                { title: "Plan Together Snorkeling & Island Tour (10 person)", price: 7000000, location: 'Nusa Lembongan, Bali', person: 10, image: 'images/MantaBaySnorkeling.webp' }, 
            ],
            activityInfo: [
                { title: "Full Description", description: "Start your adventure with a comfortable shuttle service to hotels in the area. Upon arrival at the pier, you will meet a guide who will provide safety guidance. Next, you will receive snorkeling equipment. Feel the excitement of swimming with various types of colorful tropical fish and beautiful coral reefs in the waters of Manta Bay, Crystal Bay and Toyapakeh Wall Penida. If you're lucky, you can also see a 5 meter wide stingray passing through the shallow sea!" },
                { title: "Includes", description: "Shuttle service, Snorkeling equipment, Fast boat & van ride, Instructions from a guide." },
                { title: "Not suitable for", description: [
                    "People who has effects of alcohol or drugs",
                    "Children under 3 years, Over the age of 65 years",
                    "Those who have a history of heart diseases",
                ] },
                { title: "Note", description: [
                    " The first rule of snorkeling is to not touch anything while in the water. Don't use corals as a footstool. Do not put or take anything on or out of the ecosystem.",
                ] },
            ],
            risks: [
                "Exposure to wildlife and sharp reefs",
                "Risk of cardiac arrest, causing drowning.",
                "Risks of hypothermia because of the temperature of the water.",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "How long is the tour?", answer: "The whole will last around 3-8 hours, depending on which tour you are choosing." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "Can the shuttle service pick me up from my hotel?", answer: "You can discuss with the host about using the shuttle services from us." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "What should first timers do?", answer: "At the beginning of the trip, there will be a stand by guide who will accompany help you throughout the tour." },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "Where is the nearest hotels from you guys?", answer: "Nearby you could stay at Paus Putih Hotel or Pemedal Beach Resort." },
            ],
            hotelsNearby: [
                "Paus Putih Hotel",
                "Pemedal Beach Resort",
            ],
            howToGetThere: [
                "Shuttle service provided by the host.",
                "Motorcycle",
            ],
            whatYouNeed: [
                "Sunblock",
                "Spare Clothes",
            ],
        },
    },
    {
        id: 'activity9',
        name: 'Mount Batur 4WD Jeep',
        location: 'Mount Batur, Bali',
        guestsAllowed: 4,
        dateAvailable: '2024-12-20',
        price: '500.000',
        priceForFilter: 500000,
        image: 'images/MountBaturSunriseTrekking.jpg',
        image2: 'images/mountBaturSunriseTreking2.jpg',
        image3: 'images/mountBaturSunriseTreking3.jpg',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d505039.7536455029!2d114.8278587!3d-8.5359242!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd1f5b5b3bd67fd%3A0xc1ae7b256ecb3c51!2sBatur%20Jeep%20Tour!5e0!3m2!1sen!2sid!4v1732770656088!5m2!1sen!2sid',
        rating: '4.5 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'water',
        openHours: '9 am - 4 pm',
        description: "Located in Kintamani District, this area is very popular as the start of your adventure in Bali. Take a 4WD Jeep along the road to the most ideal location to see the sunrise on the mountain. Relax for a moment and chat with other tourists while waiting for the sun to rise from the peak. Admire the surrounding plains that resemble the moon as the sun slowly shines across the horizon. Don't forget to take photos of spectacular and Instagrammable views that will amaze your friends and family at home!",
        details: {
            highlights: [
                "Watch a stunning sunrise over one of Bali's most active volcanoes, Mount Batur.",
                "After sunrise, explore the world-famous black lava area, caused by an eruption hundreds of years ago.",
                "This activity is perfect for those who want to watch the sunrise on Mount Batur without having to climb!",
            ],
            packages: [
                { title: "Short Trip (1200 MASL)", price: 500000, location: 'Mount Batur, Bali', person: 1, image: 'images/MountBaturSunriseTrekking.jpg' },
                { title: "RegularTrip (1450 MASL) Rp 807.692", price: 807692, location: 'Mount Batur, Bali', person: 1, image: 'images/MountBaturSunriseTrekking.jpg' },
                { title: "Plan Together Regular Trip (1459 MASL)", price: 760000, location: 'Mount Batur, Bali', person: 4, image: 'images/MountBaturSunriseTrekking.jpg' }, 
            ],
            activityInfo: [
                { title: "Full Description", description: "Located in Kintamani District, this area is very popular as the start of your adventure in Bali. Take a 4WD Jeep along the road to the most ideal location to see the sunrise on the mountain. Relax for a moment and chat with other tourists while waiting for the sun to rise from the peak. Admire the surrounding plains that resemble the moon as the sun slowly shines across the horizon. Don't forget to take photos of spectacular and Instagrammable views that will amaze your friends and family at home!" },
                { title: "Includes", description: "Hotel pickup service, English speaking guide, a Jeep, Jeep driver" },
                { title: "Not suitable for", description: [
                    "People who has effects of alcohol or drugs",
                    "Children under 3 years, Over the age of 65 years",
                    "Those who have a history of heart diseases",
                ] },
                { title: "Note", description: [
                    "Choose between two stunning viewpoints, on Mount Batur or its caldera.",
                ] },
            ],
            risks: [
                "Exposure to volcanic fine dust",
                "Risk of an eruption",
                "Risk of a failure of the jeep.",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "Do you guys provide pick up services?", answer: "Yes! You can contact our host to arrange the pick up." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "Do you guys provide a translator?", answer: "No, but our guides are english speakers." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "What time does the tour starts?", answer: "Our tour starts at 02:30" },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "Where is the nearest hotels from you guys?", answer: "You could stay at The Kayon Jungle Resort or Padma Rsort Ubud." },
            ],
            hotelsNearby: [
                "The Kayon Jungle Resort",
                "Padma Resort Ubud",
            ],
            howToGetThere: [
                "Our pickup up service",
                "Taxis",
            ],
            whatYouNeed: [
                "Trekking pants ",
                "Warm clothes",
            ],
        },
    },
    {
        id: 'activity10',
        name: 'ATV and Ayung River Rafting',
        location: 'Bongkasa Pertiwi, Bali',
        guestsAllowed: 14,
        dateAvailable: '2024-12-20',
        price: '997.500',
        priceForFilter: 997500,
        image: 'images/ATV and Ayung Eiver Rafting.webp',
        image2: 'images/ATV and Ayung Eiver Rafting2.webp',
        image3: 'images/ATV and Ayung Eiver Rafting3.webp',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3946.3256947099817!2d115.2489186!3d-8.4676752!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd222e7fe2ace21%3A0x404981b6a4195907!2sBali%20Rafting%20Ayung%20River!5e0!3m2!1sid!2sid!4v1732770690967!5m2!1sid!2sid',
        rating: '4.5 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'water',
        openHours: '8 am - 6 pm',
        description: "Take on the thrill of river rafting along Bali's Ayung River in Ubud! Paddle through stunning scenery, surrounded by lush rainforests, majestic waterfalls, and breathtaking gorges. After an action-packed journey down the river, enjoy a delicious Indonesian buffet lunch. For those seeking even more adventure, choose to visit the beautiful Kanto Lampo and Tibumana Waterfalls, explore the iconic Tegalalang Rice Terrace.",
        details: {
            highlights: [
                "Come on, take part in fun rafting with friends and family. On your rafting trip, see a number of beautiful natural waterfalls.",
                "Put on a helmet, wear boots, and prepare yourself because you will be riding an ATV to the rural area of Bongkasa Pertiwi.",
                "Want a longer ATV ride? If so, order to play ATV for 2 hours!",
            ],
            packages: [
                { title: "2-3 package (per person)", price: 997500, location: 'Bongkasa Pertiwi, Bali', person: 1, image: 'images/ATV and Ayung Eiver Rafting.webp' },
                { title: "4-6 package (per person)", price: 822500, location: 'Bongkasa Pertiwi, Bali', person: 1, image: 'images/ATV and Ayung Eiver Rafting.webp' },
                { title: "Plan Together 7-14 package (per person)", price: 660002, location: 'Bongkasa Pertiwi, Bali', person: 1, image: 'images/ATV and Ayung Eiver Rafting.webp' },
            ],
            activityInfo: [
                { title: "Full Description", description: "Take on the thrill of river rafting along Bali's Ayung River in Ubud! Paddle through stunning scenery, surrounded by lush rainforests, majestic waterfalls, and breathtaking gorges. After an action-packed journey down the river, enjoy a delicious Indonesian buffet lunch. For those seeking even more adventure, choose to visit the beautiful Kanto Lampo and Tibumana Waterfalls, explore the iconic Tegalalang Rice Terrace." },
                { title: "Includes", description: "Helmet, Pair of boots, Shower facility, Rafting equipments, Mini off-roads, Equipped instructors" },
                { title: "Not suitable for", description: [
                    "Non-swimmers",
                    "Children under the age of 6",
                    "People with the fear of water",
                ] },
                { title: "Note", description: [
                    "You'll be helped by a friendly and hands-on guide(who speaks Korean and English) for a hassle-free day!",
                ] },
            ],
            risks: [
                "Exposure to wildlife and rough water flow.",
                "Risk of complication of the equipments.",
                "Unpredicted weather conditions.",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "How long is the tour?", answer: "On average, our tour lasts for 8 hours." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "Are you guys korean-speaker friendly?", answer: "Yes! Our guides speaks Korean and also English." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "Where is the nearest hotels from you guys?", answer: "You could either choose between Ayung Rosort Ubud or Tjampuhan Hotel." },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "What is the age requirement?", answer: "You have to be 13 and above, and for chidren 6-12." },
            ],
            hotelsNearby: [
                "Ayung Resort Ubud",
                "Hotel Tjampuhan",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Swimming Attire",
                "Sunblock",
            ],
        },
    },
    {
        id: 'activity11',
        name: 'Bali Parasailing Adventure',
        location: 'Tanjung Benoa, Bali',
        guestsAllowed: 2,
        dateAvailable: '2024-12-15',
        price: '625.000',
        priceForFilter: 625000,
        image: 'images/Bali Parasailing Adventure.webp',
        image2: 'images/Bali Parasailing Adventure2.webp',
        image3: 'images/Bali Parasailing Adventure3.webp',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3943.273188672866!2d115.21995497382318!3d-8.760347089442426!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd243a5d66ebd05%3A0xb08255579cbf73bf!2sParasailing%20Bali!5e0!3m2!1sen!2sid!4v1732770735507!5m2!1sen!2sid',
        rating: '4.9 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'water',
        openHours: '8 am - 3 pm',
        description: "Parasailing , also known as parascending, is an exhilarating activity where individuals are harnessed to a modified parachute canopy that is designed to ascend into the air when towed behind a motor vehicle on land; or a recreational boat over water.",
        details: {
            highlights: [
                "Experience the thrill of being a bird first hand by flying over the ocean on a 10-minute parasailing adventure",
                "Witness stunning views from above as you glide over Bali's beautiful beaches while taking aerial photos",
                "Starting from the middle of the sea, you can fly alone or with your friends at the same time",
            ],
            packages: [
                { title: "One Person", price: 625000, location: 'Tanjung Benoa, Bali', person: 1, image: 'images/Bali Parasailing Adventure.webp' },
                { title: "Two Person", price: 975000, location: 'Tanjung Benoa, Bali', person: 2, image: 'images/Bali Parasailing Adventure.webp' },
                { title: "Parasailing Adventure + Donut Boat + Jet Ski + Banana Boat One Person", price: 887500, location: 'Tanjung Benoa, Bali', person: 1, image: 'images/Bali Parasailing Adventure.webp' },                
            ],
            activityInfo: [
                { title: "Full Description", description: "Parasailing , also known as parascending, is an exhilarating activity where individuals are harnessed to a modified parachute canopy that is designed to ascend into the air when towed behind a motor vehicle on land; or a recreational boat over water." },
                { title: "Includes", description: "Bottled water, all necessary safety equipment, rent a locker, towels, soap, shampoo, Insurance provided by the operator (for participants aged 9-70 years) Parasailing (4 minutes) Pick up at hotel (For bookings of at least 2 people)" },
                { title: "Not suitable for", description: [
                    "Pregnant women",
                    "Fear of heights",
                    "Medical condition",
                ] },
                { title: "Note", description: [
                    "You can choose to fly by yourself or together in group of 2 or 3 people",
                ] },
            ],
            risks: [
                "Bad weather: Strong winds can cause mechanical failures or snap towlines. ",
                "Boat collisions: If the operator is distracted, intoxicated, or loses control of the boat, it can collide with other boats. ",
                "Crushing injuries: Parasailers can hit objects like boats or buildings with force, which can cause internal bleeding and broken bones. ",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "How long will the total trip be?", answer: "1.5 hours." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "Will the trips be rescheduled when there is bad weather?", answer: "Yes the trips will be rescheduled when there is bad weather." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "Is it safe? What is the safety procedure?", answer: "There will be two guides that will follow you throughout the trip on the front and on the back of the line. And there will be staffs along the track." },
            ],
            hotelsNearby: [
                "Novotel Bali Benoa",
                "Grand Mirage Resort",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Spare clothes",
                "Sunblock",
            ],
        },
    },
    {
        id: 'activity12',
        name: 'Kecak Fire Dance Tour',
        location: 'Ubud, Bali',
        guestsAllowed: 1,
        dateAvailable: '2024-12-10',
        price: '100.000',
        priceForFilter: 100000,
        image: 'images/Kecak Fire Dance Tour2.webp',
        image2: 'images/Kecak Fire Dance Tour.webp',
        image3: 'images/Kecak Fire Dance Tour3.webp',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d252433.34825746156!2d115.01930153555028!3d-8.665750688681163!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd23dc90ff3009f%3A0xc4cd0ec215be61a6!2sKecak%20%26%20Fire%20Dance%20-%20Ubud%20Kaja%20at%20Pura%20Dalem%20Ubud!5e0!3m2!1sen!2sid!4v1732770783100!5m2!1sen!2sid',
        rating: '4.7 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'fire',
        openHours: '7 pm - 8 pm',
        description: "Prepare to be enchanted by a stunning Kecak dance performance, a captivating performance of the traditional Balinese Kecak dance. Against the backdrop of the majestic Uluwatu Temple. As the sun begins to set, the rhythmic singing of the performers, known as “kecak” fills the sky, creating an otherworldly atmosphere. Balinese dancers, dressed in vibrant costumes, skillfully depict the characters of the Ramayana story, with Prince Rama taking center stage.",
        details: {
            highlights: [
                "Be enchanted by the hypnotic Kecak dance, dazzling flames and colorful cultural costumes",
                "Book via Klook and buy tickets to watch the famous Ubud Kecak and Fire Dance Show! ",
                "Get your guaranteed seat in advance by booking via Klook and redeem your ticket at the ticket counter (online reservation line",
            ],
            packages: [
                { title: "One Person", price: 100000, location: 'Ubud, Bali', person: 3, image: 'images/Kecak Fire Dance Tour2.webp' },                
            ],
            activityInfo: [
                { title: "Full Description", description: "Prepare to be enchanted by a stunning Kecak dance performance, a captivating performance of the traditional Balinese Kecak dance. Against the backdrop of the majestic Uluwatu Temple. As the sun begins to set, the rhythmic singing of the performers, known as “kecak” fills the sky, creating an otherworldly atmosphere. Balinese dancers, dressed in vibrant costumes, skillfully depict the characters of the Ramayana story, with Prince Rama taking center stage." },
                { title: "Includes", description: "Akses masuk ke wahana/atraksi berikut: Tiket Pertunjukan Tari Kecak & Api" },
                { title: "Not suitable for", description: [
                    "Heart Diseases",
                    "Fear of Fire",
                    "Fear of Loud Noises",
                ] },
                { title: "Note", description: [
                    "Public show",
                ] },
            ],
            risks: [
                "Risk of crowded spaces",
                "Risk of close contact with fire",
                "Risk of loud noises",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "Will there be a range limitation to the dancers?", answer: "No, there will not be a range limitation to the dancers" },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "Is it safe? What is the safety procedure?", answer: "There will be two guides that will follow you throughout the trip on the front and on the back of the line. And there will be staffs along the track." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "Can we take pictures?", answer: "Yes you can take pictures." },
            ],
            hotelsNearby: [
                "Puri Padma Hotel",
                "Ubud Tropical",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Mosquito repellent",
                "Hand Sized Fan",
            ],
        },
    },
    {
        id: 'activity13',
        name: 'Water Sport Experience',
        location: 'Tanjung Benoa, Bali',
        guestsAllowed: 10,
        dateAvailable: '2024-12-20',
        price: '15.333',
        priceForFilter: 15333,
        image: 'images/Water Sport Experience.webp',
        image2: 'images/Water Sport Experience2.webp',
        image3: 'images/Water Sport Experience3.webp',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3943.3452430318603!2d115.21787657382296!3d-8.753550489352083!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd243a5a69cf595%3A0x1c113a5e73591118!2sMawar%20Kuning%20Dive%20%26%20Water%20Sports!5e0!3m2!1sen!2sid!4v1732770865709!5m2!1sen!2sid',
        rating: '4.5 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'water',
        openHours: '9 am - 5 pm',
        description: "You can book this package and get the chance to try several activities in a day! You can scream as loud as you can when you ride a flying fish, laugh until you cry with your friends on a banana boat, or feel the sensation of being like a pirate when you try out a jet ski!",
        details: {
            highlights: [
                "Choose from a variety of exciting activities including banana boat rides, fly fishing, jet skiing, and more!",
                "Challenge your skills as you slide, twist and twirl through the waters on a high-speed banana boat and jet ski rides!",
                "The duration of each activity is guaranteed! If you feel dissatisfied with the time, you can repeat the activity for that day. Any complaints regarding the duration of activities made after you have left the venue will not be accommodated.",
            ],
            packages: [
                { title: "15 minutes Banana boat (minimum of 2 person) (per person)", price: 60000, location: 'Tanjung Benoa, Bali', person: 3, image: 'images/Water Sport Experience.webp' },
                { title: "15 minutes Jetski with an instructor", price: 15333, location: 'Tanjung Benoa, Bali', person: 3, image: 'images/Water Sport Experience.webp' },
                { title: "Plan together Package A (minimum of 2): Parasailing Adventure(1x Flying), Banana Boat, Jetski with an instructor", price: 425000, location: 'Tanjung Benoa, Bali', person: 3, image: 'images/Water Sport Experience.webp' },                
            ],
            activityInfo: [
                { title: "Full Description", description: "You can book this package and get the chance to try several activities in a day! You can scream as loud as you can when you ride a flying fish, laugh until you cry with your friends on a banana boat, or feel the sensation of being like a pirate when you try out a jet ski!" },
                { title: "Includes", description: "Banana boat, Jetski, Flying fish,Parasailing" },
                { title: "Not suitable for", description: [
                    "Non-swimmers",
                    "Those under the age of 13",
                    "People with the fear of water",
                ] },
                { title: "Note", description: [
                    "We provide pickup services right in front of your door! Contact our host and book the event.",
                ] },
            ],
            risks: [
                "Machine Failure",
                "Unpredicted weather condition",
                "Risks of drowning",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "What should first timers do?", answer: "At the beginning of the trip, there will be a stand by instructorwho will accompany help you along the journey." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "Is it safe?", answer: "We can ensure you that our intructors are well capable of doimg their job." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "Where is the nearest hotels from you guys?", answer: "You could either choose between Ion Bali Benoa or Core Hotel Benoa." },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "What is the operational time?", answer: "We are open at 9 in the morning and closes at 5 PM" },
            ],
            hotelsNearby: [
                "Ion Bali Benoa",
                "Core Hotel Benoa",
            ],
            howToGetThere: [
                "Our pickup services",
                "Motorcycles",
            ],
            whatYouNeed: [
                "Subblock",
                "Spare Clothes",
            ],
        },
    },
    {
        id: 'activity14',
        name: 'Telaga Waja Rafting',
        location: 'Bali Tubing & Rafting, Bali',
        guestsAllowed: 4,
        dateAvailable: '2024-12-20',
        price: '307.500',
        priceForFilter: 307500,
        image: 'images/Telaga Waja Rafting.jpg',
        image2: 'images/telagaWajaRafting2.jpg',
        image3: 'images/telagaWajaRafting3.jpg',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3946.7749629236905!2d115.4344463!3d-8.4237478!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd21ba1c2cb0a1d%3A0x29da9102688f3869!2sBTR%20(Bali%20Tubing%20%26%20Rafting)%20Starting%20Point!5e0!3m2!1sid!2sid!4v1732770895245!5m2!1sid!2sid',
        rating: '4.5 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'water',
        openHours: '10 am - 6 pm',
        description: "Travel the off-beaten path in Bali and go white water rafting down the Telaga Waja River. Despite being in a quiet and secluded area, white water rafting is a wild (albeit safe) water sport that's perfectly suited for nature lovers and adrenaline junkies alike. A professional team will assist you, so there's nothing to worry about. Throughout the 14-kilometer course, you'll get to see beautiful panoramas of mountains, waterfalls, rice fields, and stone cliffs. ",
        details: {
            highlights: [
                "White water raft through eastern Bali at Telaga Waja River",
                "Enjoy the panorama of mountains, stone cliffs, and more while cruising downstream",
                "Experience a lesser-known side of Balinese culture with green scenery",
            ],
            packages: [
                { title: "White Water Rafting Domestic (Without Transport)", price: 307500, location: 'Bali Tubing & Rafting, Bali', person: 4, image: 'images/Telaga Waja Rafting.jpg' },
                { title: "White Water Rafting for 2-4 Person", price: 1046932, location: 'Bali Tubing & Rafting, Bali', person: 4, image: 'images/Telaga Waja Rafting.jpg' }, 
            ],
            activityInfo: [
                { title: "Full Description", description: "Travel the off-beaten path in Bali and go white water rafting down the Telaga Waja River. Despite being in a quiet and secluded area, white water rafting is a wild (albeit safe) water sport that's perfectly suited for nature lovers and adrenaline junkies alike. A professional team will assist you, so there's nothing to worry about. Throughout the 14-kilometer course, you'll get to see beautiful panoramas of mountains, waterfalls, rice fields, and stone cliffs." },
                { title: "Includes", description: "Professional guide, lunch, shower room, safety equipment, towels" },
                { title: "Not suitable for", description: [
                    "age below 8 and over 60",
                    "pregnant woman",
                    "People with a fear of water or strong currents",
                ] },
                { title: "Note", description: [
                    "Telaga Waja Rafting offers a 14-kilometer adventure through scenic landscapes, guided by professionals for a safe experience. Enjoy views of mountains, waterfalls, and stone cliffs. Includes lunch, shower access, safety gear, and towels. Not recommended for children under 8, adults over 60, pregnant women, or those with a fear of water.",
                ] },
            ],
            risks: [
                "Minor Injuries: Possible minor bruises or muscle soreness from physical activity in strong currents.",
                "Weather Conditions: Activity may be delayed or rescheduled due to heavy rain or water flow changes.",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "Is any prior rafting experience required to join?", answer: "No prior experience is needed; the activity is designed for beginners and includes guidance from a professional." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "Will there be photos available to purchase after the activity?", answer: "Yes, professional photos of the experience are usually available for purchase afterward." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "What happens if it rains on the day of the activity?", answer: "In case of heavy rain or unsafe water conditions, the activity may be delayed or rescheduled for safety reasons." },
            ],
            hotelsNearby: [
                "Tapa Agung View",
                "Besakih Homestay & Villa",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Spare clothes and swimwear",
                "Sunscreen",
            ],
        },
    },
    {
        id: 'activity15',
        name: 'River Rafting Adventure in Ubud',
        location: 'Ubud, Bali',
        guestsAllowed: 10,
        dateAvailable: '2024-12-20',
        price: '239.063',
        priceForFilter: 239063,
        image: 'images/River Rafting Adventure in Ubud.jpg',
        image2: 'images/River Rafting Adventure in Ubud2.jpg',
        image3: 'images/River Rafting Adventure in Ubud3.jpg',
        locationGMAPS: 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15782.787125944504!2d115.2268973!3d-8.5287902!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd23c57cefd9c45%3A0xfa4e8528f05c6217!2sAngkasa%20Semana%20Rafting!5e0!3m2!1sen!2sid!4v1732770933947!5m2!1sen!2sid',
        rating: '4.5 <i class="fa-solid fa-star fa-lg" style="color: #FFD43B;"></i>',
        category: 'water',
        openHours: '8 am - 5 pm',
        description: "Take on the thrill of river rafting along Bali's Ayung River in Ubud! Paddle through stunning scenery, surrounded by lush rainforests, majestic waterfalls, and breathtaking gorges. After an action-packed journey down the river, enjoy a delicious Indonesian buffet lunch. For those seeking even more adventure, choose to visit the beautiful Kanto Lampo and Tibumana Waterfalls, explore the iconic Tegalalang Rice Terrace, or add an ATV ride to your day.",
        details: {
            highlights: [
                "If you have a fondness for rafting, then take the opportunity to take on the waters of the Ayung River!",
                "Enjoy spectacular views of the verdant rainforest, majestic waterfalls, and breathtaking gorges in the area",
                "After an exhilarating time paddling down the river, you’ll feast on an authentic Indonesia buffet lunch",
            ],
            packages: [
                { title: "River Rafting by Ubud Rafting (one person)", price: 239063, location: 'Ubud, Bali', person: 1, image: 'images/River Rafting Adventure in Ubud.jpg' },
                { title: "River Rafting by Ubud Group of 2-4 (Per Person)", price: 252500, location: 'Ubud, Bali', person: 1, image: 'images/River Rafting Adventure in Ubud.jpgimages/5gx.png' },
                { title: "Plan Together River Rafting by Ubud  Group of 5+ (Per Person)", price: 216500, location: 'Ubud, Bali', person: 1, image: 'images/River Rafting Adventure in Ubud.jpg' },
            ],
            activityInfo: [
                { title: "Full Description", description: "Take on the thrill of river rafting along Bali's Ayung River in Ubud! Paddle through stunning scenery, surrounded by lush rainforests, majestic waterfalls, and breathtaking gorges. After an action-packed journey down the river, enjoy a delicious Indonesian buffet lunch. For those seeking even more adventure, choose to visit the beautiful Kanto Lampo and Tibumana Waterfalls, explore the iconic Tegalalang Rice Terrace, or add an ATV ride to your day." },
                { title: "Includes", description: "Admission to attractions, lunch, all equipments, saferty gear" },
                { title: "Not suitable for", description: [
                    "Individuals with high blood pressure, epilepsy, heart disease, asthma, or other serious medical conditionsrs",
                    "Pregnant women",
                    "Persons with disabilities (PWDs)",
                ] },
                { title: "Note", description: [
                    "This rafting activity is a shared experience with other participants, with each boat carrying up to 6 passengers and guided by a professional rafting guide. A water-resistant bag is provided to keep belongings dry, though it’s recommended to leave valuables at home as the operator is not liable for lost or damaged items.",
                ] },
            ],
            risks: [
                "Physical Strain: Paddling and navigating may cause muscle soreness or minor bruises.",
                "Water Hazards: Strong currents, rocks, and debris require careful attention to the guide’s instructions.",
                "Sun Exposure: Prolonged sun exposure can lead to sunburn or dehydration; sunscreen and water are recommended.",
            ],
            faq: [
                { id:"plusMinus1", id2:"faq1", togglefaq:"toggleFAQ(1)", question: "How long does the rafting experience last?", answer: "The rafting experience typically lasts around 1.5 to 2 hours." },
                { id:"plusMinus2", id2:"faq2", togglefaq:"toggleFAQ(2)", question: "Are personal belongings safe during the activity?", answer: "A water-resistant bag is provided, but it’s best to leave valuables at home to avoid damage or loss." },
                { id:"plusMinus3", id2:"faq3", togglefaq:"toggleFAQ(3)", question: "Is food provided after the activity?", answer: "Yes, a buffet lunch featuring authentic Indonesian dishes is provided at the end of the rafting session." },
                { id:"plusMinus4", id2:"faq4", togglefaq:"toggleFAQ(4)", question: "What is the meeting time, and where should participants arrive?", answer: "Participants should arrive at the meet-up location 30 minutes before the scheduled time, with a meeting point at Infinity Bali Adventure in Ubud." },
            ],
            hotelsNearby: [
                "Outpost Ubud Penestanan",
                "Labak River Hotel by EPS",
            ],
            howToGetThere: [
                "Motorcycles",
                "Taxis",
            ],
            whatYouNeed: [
                "Spare clothes",
                "Toiletries",
            ],
        },
    }
];

export default activities;